### PR TITLE
Update gutter signs

### PR DESCRIPTION
**Pull request by sscherfke**
The new signs look a bit better and only use one character instead of two, which makes the gutter a bit smaller.

### CODE REVIEW

**Comment by mgedmin** [comment]
Thank you for the PR!

Do you have a screenshot of how this looks?

**Comment by sscherfke** [comment]
Bildschirmfoto 2020-08-27 um 20 48 51
There you go :)

**Comment by mgedmin** [comment]
Thank you!

May I use your screenshot in the README?

**Comment by sscherfke** [comment]
Yes, you can! :)

**Comment by mgedmin** [comment]
Thank you!

**Pull request merged**
